name: chat_app
description: "A comprehensive real-time chat application with modern UI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  
  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Socket.IO
  socket_io_client: ^2.0.3+1
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Media & Files
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  cached_network_image: ^3.3.1
  image_cropper: ^9.1.0
  video_player: ^2.8.6
  chewie: ^1.8.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  
  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.1
  uuid: ^4.4.0
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  equatable: ^2.0.5
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.1.0
  badges: ^3.1.2
  
  # Notifications
  flutter_local_notifications: ^17.1.2
  
  # Camera & Video
  camera: ^0.10.5+9
  
  # Animations
  animations: ^2.0.11
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700